# -*- coding: utf-8 -*-
"""ProgettoR.O.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yigx14xXY17TfBICPkzmlYdPXWMFl5ZR

##TOOL DI VISUALIZZAZIONE DELLA SOLUZIONE
Questa funzione permette di rappresentare graficamente una soluzione del problema di Job Shop.
"""

# ==========================================
# IMPORTAZIONI
# ==========================================
import os
import matplotlib

if os.environ.get('DISPLAY'):
    try:
        import tkinter  # noqa: F401
        matplotlib.use('TkAgg')
    except Exception:
        matplotlib.use('Agg')
else:
    matplotlib.use('Agg')

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np
import collections
from itertools import takewhile
from ortools.sat.python import cp_model
import math
import random
import copy
import time
import pandas as pd
import seaborn as sns


def _sanitize_filename(text):
    clean = ''.join(ch if ch.isalnum() or ch in ('_', '-', ' ') else '_' for ch in str(text))
    clean = '_'.join(clean.strip().split())
    return clean[:120] if clean else 'plot'


def safe_show(fig=None, title=None):
    """Mostra il grafico se il backend è interattivo; altrimenti salva PNG in ./plots."""
    if fig is None:
        fig = plt.gcf()

    backend = plt.get_backend().lower()
    if 'agg' in backend:
        plots_dir = os.path.join(os.path.dirname(__file__), 'plots')
        os.makedirs(plots_dir, exist_ok=True)

        if title:
            filename = f"{_sanitize_filename(title)}.png"
        else:
            filename = f"plot_{len(plt.get_fignums()):03d}.png"

        output_path = os.path.join(plots_dir, filename)
        fig.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f"[grafico salvato] {output_path}")
        plt.close(fig)
        return

    plt.show()


def save_terminal_table_as_image(instance_name, results, optimum):
    rows = []
    for alg, ms in results.items():
        gap_pct = ((ms - optimum) / optimum * 100) if optimum > 0 else 0
        gap_units = ms - optimum
        rows.append({
            'Algorithm': alg.replace('\n', ' '),
            'Makespan': int(ms),
            'Gap %': f"{gap_pct:.2f}%",
            'Gap (units)': int(gap_units)
        })

    df = pd.DataFrame(rows)
    fig_h = max(2.2, 0.6 * len(df) + 1.6)
    fig, ax = plt.subplots(figsize=(10, fig_h))
    ax.axis('off')
    ax.set_title(f"Results Table - {instance_name}", fontsize=14, fontweight='bold', pad=12)

    table = ax.table(
        cellText=df.values,
        colLabels=df.columns,
        cellLoc='center',
        colLoc='center',
        loc='center'
    )
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1, 1.25)

    for (row, col), cell in table.get_celld().items():
        if row == 0:
            cell.set_text_props(weight='bold')
            cell.set_facecolor('#DCEEFF')

    plt.tight_layout()
    safe_show(fig, title=f"tabella_risultati_{instance_name}")


def plot_job_shop(results, title="Job Shop Scheduling Gantt Chart"):
    """
    Parametri:
    results: Lista di dizionari. Ogni dizionario deve avere:
             'job': id del job (int o str)
             'machine': id della macchina (int o str)
             'start': istante di inizio (float o int)
             'duration': durata del task (float o int)
             'op': id dell'operazione
    """

    if not results:
        print("Nessun dato da visualizzare.")
        return

    # 1. Identifica macchine e job unici
    # Usiamo sorted per avere un ordine consistente negli assi e nei colori
    unique_jobs = sorted(list({str(res['job']) for res in results}))
    unique_machines = sorted(list({str(res['machine']) for res in results}))

    # 2. Setup Colormap (tab20 offre 20 colori distinti)
    colors = plt.cm.tab20(range(len(unique_jobs)))
    job_colors = {job: colors[i % 20] for i, job in enumerate(unique_jobs)}

    # 3. Setup del Grafico
    fig, ax = plt.subplots(figsize=(12, 6))
    bar_height = 0.6  # Spessore delle barre

    # Mappa le macchine a posizioni verticali (0, 1, 2...)
    machine_map = {m: i for i, m in enumerate(unique_machines)}

    max_time = 0

    # 4. Disegno delle barre
    for res in results:
        # Estrazione dati con gestione stringhe/numeri
        job = str(res['job'])
        machine = str(res['machine'])
        start = res['start']
        duration = res['duration']
        op_id = res['op']

        y_pos = machine_map[machine]

        # Disegno del blocco orizzontale
        ax.broken_barh([(start, duration)],
                       (y_pos - bar_height/2, bar_height),
                       facecolors=job_colors[job],
                       edgecolor='black',
                       linewidth=1,
                       alpha=0.8)

        # Creazione etichetta (es: J1-O2)
        label = f"J{job}-O{op_id}"

        # Posizionamento testo al centro della barra
        ax.text(start + duration/2, y_pos, label,
                ha='center', va='center', color='white',
                fontweight='bold', fontsize=9)

        # Aggiornamento tempo massimo per i limiti dell'asse X
        max_time = max(max_time, start + duration)

    # 5. Formattazione Assi e Griglia
    ax.set_xlabel('Tempo (Unità temporali)', fontweight='bold')
    ax.set_ylabel('Risorse (Macchine)', fontweight='bold')
    ax.set_title(title, fontsize=14, pad=15)

    # Imposta i nomi delle macchine sull'asse Y
    ax.set_yticks(range(len(unique_machines)))
    ax.set_yticklabels([f"Macchina {m}" for m in unique_machines])

    # Configura i tick dell'asse X (interi)
    ax.set_xticks(range(0, int(max_time) + 2))

    # Aggiunge una griglia leggera solo sull'asse X per facilitare la lettura dei tempi
    ax.grid(True, axis='x', linestyle='--', alpha=0.5)

    # Limiti del grafico
    ax.set_xlim(0, max_time + 1)
    ax.set_ylim(-0.5, len(unique_machines) - 0.5)

    # 6. Legenda (opzionale, utile se hai molti job)
    legend_patches = [mpatches.Patch(color=job_colors[job], label=f'Job {job}') for job in unique_jobs]
    ax.legend(handles=legend_patches, bbox_to_anchor=(1.05, 1), loc='upper left', title="Legenda Job")

    plt.tight_layout()
    safe_show(fig, title=title)

# # --- ESEMPIO DI TEST PRONTO ALL'USO --- è da togliere, mi serviva solo per vedere come funziona e ti fa capire in che formato passargli results
# if __name__ == "__main__":
#     dati_test = [
#         # Job 1: passa da Macchina A a B
#         {'job': '1', 'op': '1', 'machine': 'A', 'start': 0, 'duration': 3},
#         {'job': '1', 'op': '2', 'machine': 'B', 'start': 3, 'duration': 2},

#         # Job 2: passa da Macchina B a A
#         {'job': '2', 'op': '1', 'machine': 'B', 'start': 0, 'duration': 2},
#         {'job': '2', 'op': '2', 'machine': 'A', 'start': 3, 'duration': 4},

#         # Job 3: solo su Macchina C
#         {'job': '3', 'op': '1', 'machine': 'C', 'start': 1, 'duration': 5},
#     ]

#     plot_job_shop(dati_test) #la struttura che gli passo è una lista di dizionari

"""## Generazione Istanza del Problema

La funzione `generate_job_shop_instance` crea un'istanza semplificata di un problema di Job Shop Scheduling. Questo tipo di problema riguarda l'assegnazione di operazioni (tasks) di diversi "job" a diverse "macchine" in un ordine specifico, cercando di ottimizzare il makespan.

Ecco una scomposizione dei suoi parametri e del suo funzionamento:

### Parametri:
- `num_jobs`: Il numero di lavori (job) da generare nell'istanza. Ogni job avrà una serie di operazioni da eseguire.
- `num_machines`: Il numero di macchine disponibili. Ogni operazione di un job verrà assegnata a una di queste macchine.
- `proc_time_range`: Una tupla `(min_duration, max_duration)` che definisce l'intervallo minimo e massimo per la durata (tempo di elaborazione) di ciascuna operazione. La durata effettiva verrà scelta casualmente all'interno di questo intervallo.
- `seed`: Un valore opzionale per il seed del generatore di numeri casuali. Usarlo assicura che le istanze generate siano riproducibili (ovvero, eseguendo la funzione con lo stesso seed si otterranno sempre gli stessi risultati).

### Funzionamento:
1. **Inizializzazione**: Se viene fornito un `seed`, il generatore di numeri casuali di NumPy viene inizializzato con quel seed. Viene creata una lista vuota `instance` che conterrà tutte le operazioni generate.
2. **Definizione delle Macchine**: Viene creata una lista di `machines_list` da `0` a `num_machines - 1` per rappresentare le macchine disponibili.
3. **Generazione dei Job**: Per ogni job (`j` da `0` a `num_jobs - 1`):
   - Viene generata una `technological_sequence` casuale delle macchine. Questo significa che per ogni job, l'ordine in cui le macchine devono essere utilizzate è unico e casuale, ma ogni macchina viene visitata una sola volta per quel job (questa è una semplificazione comune per alcune varianti del Job Shop).
   - Per ogni macchina (`m_id`) nella sequenza tecnologica:
     - Viene generata una `duration` casuale per l'operazione sulla base di `proc_time_range`.
     - Un dizionario che rappresenta l'operazione viene aggiunto alla lista `instance`. Questo dizionario contiene:
       - `'job'`: L'ID del job (come stringa, partendo da '1').
       - `'op'`: L'ID dell'operazione all'interno del job (come stringa, partendo da '1').
       - `'machine'`: L'ID della macchina su cui l'operazione deve essere eseguita (come stringa).
       - `'duration'`: La durata dell'operazione.
4. **Ritorno**: La funzione restituisce la lista `instance` completa.
"""

def generate_job_shop_instance(num_jobs=4, num_machines=3, proc_time_range=(1, 10), seed=None):
    """
    Genera un'istanza piatta per un problema di Job Shop Scheduling.

    Returns:
        list: Una lista di dizionari, dove ogni dizionario è una singola operazione.
    """
    if seed is not None:
        np.random.seed(seed)

    instance = []
    machines_list = list(range(num_machines))

    for j in range(num_jobs):
        # Definiamo la sequenza tecnologica casuale per il job attuale
        technological_sequence = np.random.permutation(machines_list)

        for i, m_id in enumerate(technological_sequence):
            duration = np.random.randint(proc_time_range[0], proc_time_range[1] + 1)

            # Aggiungiamo direttamente l'operazione alla lista principale
            instance.append({
                "job": str(j + 1),
                "op": str(i + 1),
                "machine": str(m_id),
                "duration": duration
            })

    return instance #restituisce una lista di dizionari,vedi esempio sotto

# # --- ESEMPIO DI UTILIZZO --- che è da togliere ,serve solo per capire come funziona
# instance = generate_job_shop_instance(num_jobs=3, num_machines=3, proc_time_range=(2, 8), seed=42)

# # Stampa per verifica
# import pprint
# pprint.pprint(instance, sort_dicts=False)

# #esempio di output prodotto
# #[{'job': '1', 'op': '1', 'machine': '0', 'duration': 6},
# # {'job': '1', 'op': '2', 'machine': '1', 'duration': 8},
# # {'job': '1', 'op': '3', 'machine': '2', 'duration': 4},
# # {'job': '2', 'op': '1', 'machine': '1', 'duration': 8},
# # {'job': '2', 'op': '2', 'machine': '2', 'duration': 3},
# #{'job': '2', 'op': '3', 'machine': '0', 'duration': 4},
# # {'job': '3', 'op': '1', 'machine': '1', 'duration': 4},
# # {'job': '3', 'op': '2', 'machine': '0', 'duration': 6},
# # {'job': '3', 'op': '3', 'machine': '2', 'duration': 5}]"""

"""##Solver

"""

def solver(instance_data, time_limit_sec=180):
    """
    Risolve il problema Job Shop a partire da una lista di dizionari.

    Args:
        instance_data (list): Lista di dizionari {'job': str, 'op': str, 'machine': str, 'duration': int}
        time_limit_sec (int): Tempo limite in secondi per il solver.
    """

    # print("--- INIZIO ELABORAZIONE ---")

    # ==========================================
    # 1. PRE-PROCESSING DEI DATI
    # ==========================================
    # Convertiamo la lista piatta in una struttura organizzata per Job
    # jobs_data[job_index] = [(machine_id, duration), (machine_id, duration), ...]

    # Usiamo un dizionario temporaneo per raggruppare: job_id -> lista di operazioni
    temp_jobs = collections.defaultdict(list)
    unique_machines = set()

    for item in instance_data:
        # Assumiamo che i job partano da 1 nel dizionario, quindi sottraiamo 1 per averli 0-based
        j_id = int(item['job']) - 1
        op_id = int(item['op'])
        m_id = int(item['machine'])
        dur = int(item['duration'])

        #otteniamo le macchine uniche
        unique_machines.add(m_id)

        # Salviamo la tupla (operazione, macchina, durata)
        temp_jobs[j_id].append((op_id, m_id, dur))

    # Determiniamo il numero di job e macchine
    num_jobs = len(temp_jobs)
    num_machines = max(unique_machines) + 1 if unique_machines else 0

    # Costruiamo la lista finale jobs_data ordinata
    jobs_data = []
    # Ordiniamo le chiavi dei job per assicurarci di processare Job 1, poi Job 2, ecc.
    sorted_job_indices = sorted(temp_jobs.keys())

    for j in sorted_job_indices:
        # Ordina le operazioni del job j in base all'id operazione (op)
        # Questo garantisce che la sequenza tecnologica sia rispettata
        ops = sorted(temp_jobs[j], key=lambda x: x[0])

        # Estrae solo (macchina, durata) scartando l'indice op ormai inutile
        cleaned_ops = [(x[1], x[2]) for x in ops]
        jobs_data.append(cleaned_ops)

    # ==========================================
    # 2. CREAZIONE DEL MODELLO CP-SAT
    # ==========================================
    model = cp_model.CpModel()

    # Strutture dati per salvare le variabili e recuperarle dopo la risoluzione
    machine_to_intervals = collections.defaultdict(list)
    all_tasks = {} # struttura all_tasks : (job_id, task_id) -> (start_var, end_var)

    # Calcolo orizzonte temporale (Upper Bound del Makespan = somma di tutte le durate)
    horizon = sum(task[1] for job in jobs_data for task in job)

    # Variabile Obiettivo: Makespan
    makespan = model.NewIntVar(0, horizon, 'makespan')

    # 3. CREAZIONE VARIABILI E VINCOLI
    for job_id, job in enumerate(jobs_data):
        previous_end_time = None

        for task_id, task in enumerate(job):
            machine = task[0]
            duration = task[1]
            suffix = f'_{job_id}_{task_id}'

            # Variabili decisionali: inizio e fine del task
            start_var = model.NewIntVar(0, horizon, 'start' + suffix)
            end_var = model.NewIntVar(0, horizon, 'end' + suffix)

            # Variabile Intervallo (fondamentale per i vincoli di non sovrapposizione)
            interval_var = model.NewIntervalVar(start_var, duration, end_var, 'interval' + suffix)

            # Salviamo le variabili
            all_tasks[job_id, task_id] = (start_var, end_var)
            machine_to_intervals[machine].append(interval_var)

            # VINCOLO 1: Precedenza Tecnologica (Chain constraint)
            # Il task attuale deve iniziare dopo la fine del precedente nello stesso job
            if previous_end_time is not None:
                model.Add(start_var >= previous_end_time)

            previous_end_time = end_var

        # VINCOLO 2: Definizione Makespan
        # Il makespan deve essere >= alla fine dell'ultima operazione di questo job
        model.Add(makespan >= previous_end_time)

    # VINCOLO 3: Risorse Disgiuntive (No Overlap)
    # Su ogni macchina, gli intervalli non possono sovrapporsi
    for machine in range(num_machines):
        model.AddNoOverlap(machine_to_intervals[machine])

    # 4. OBIETTIVO
    model.Minimize(makespan)

    # ==========================================
    # 5. RISOLUZIONE
    # ==========================================
    solver = cp_model.CpSolver()
    solver.parameters.max_time_in_seconds = time_limit_sec

    # print("Avvio del solver...")
    status = solver.Solve(model)

    # 6. OUTPUT E VISUALIZZAZIONE
    if status == cp_model.OPTIMAL or status == cp_model.FEASIBLE:
        print(f'\nSoluzione Trovata!')
        print(f'Status: {solver.StatusName(status)}')
        print(f'Makespan Ottimo: {solver.ObjectiveValue()}')
        print('-' * 65)
        return int(solver.ObjectiveValue())
    else:
        print("Nessuna soluzione trovata nel tempo limite.")
        return None

"""#Convertitore Benchmark In Lista Di DIzionari
lista dei benchmark al link: https://github.com/tamy0612/JSPLIB/blob/master/instances/ta40
"""

def parse_benchmark_instance(raw_text):
    """
    Legge una stringa in formato standard OR-Library (Lawrence/Fisher-Thompson)
    e la converte nel formato lista di dizionari per il tuo solver.

    Formato standard:
    - Prima riga: <num_jobs> <num_machines>
    - Righe successive: coppie (macchina, durata) per ogni operazione del job.
    """
    lines = raw_text.strip().split('\n')

    # Leggi intestazione
    # A volte ci sono spazi extra, quindi facciamo split e filter
    header = list(filter(None, lines[0].strip().split()))
    num_jobs = int(header[0])
    num_machines = int(header[1])

    instance_data = []

    # I job nel file iniziano dalla riga 1 (dopo l'header)
    for job_idx, line in enumerate(lines[1:]):
        if job_idx >= num_jobs: break # Sicurezza

        parts = list(filter(None, line.strip().split()))

        # Il formato standard è: machine_id duration machine_id duration ...
        # Attenzione: i dati grezzi sono coppie.

        op_counter = 1
        i = 0
        while i < len(parts):
            machine_id = int(parts[i])
            duration = int(parts[i+1])

            instance_data.append({
                'job': str(job_idx + 1),      # 1-based per coerenza col tuo codice
                'op': str(op_counter),
                'machine': str(machine_id),
                'duration': duration
            })

            op_counter += 1
            i += 2

            # esmepio variabile instance data:
            # [
            #   {'job': '1', 'op': '1', 'machine': '2', 'duration': 1},
            #   {'job': '1', 'op': '2', 'machine': '0', 'duration': 3},...
            # ]

    return instance_data, num_jobs, num_machines

"""##Parser Dell'istanza
Organizza la lista raggruppandola per job: job_id -> lista operazioni ordinate.
cosi facendo io ho ogni job raggruppato e le operazioni di ogni job in ordine di sequenza (op 1,2,3...)
"""

def parse_instance(instance):
    jobs = {}
    for item in instance:
        j_id = item['job']
        if j_id not in jobs:
            jobs[j_id] = []
        jobs[j_id].append(item)

    # Ordiniamo le operazioni di ogni job per sequenza
    for j in jobs:
        jobs[j].sort(key=lambda x: int(x['op']))

    # esmepio variabile jobs:
      #{
      #     # JOB 0
      #     0: [
      #         (2, 1),  # Vai su Macchina 2 per 1 min
      #         (0, 3),  # Poi su Macchina 0 per 3 min
      #         (1, 6),  # Poi su Macchina 1 per 6 min
      #         (3, 7),  # ...
      #         (5, 3),
      #         (4, 6)
      #     ],

      #     # JOB 1
      #     1: [
      #         (1, 8),  # Vai su Macchina 1 per 8 min
      #         (2, 5),  # Poi su Macchina 2 per 5 min
      #         (4, 10), # ...
      #         (5, 10),
      #         (0, 10),
      #         (3, 4)
      #     ],

      #     # JOB 2
      #     2: [
      #         (2, 5),  # Vai su Macchina 2 per 5 min
      #         (3, 4),  # Poi su Macchina 3 per 4 min
      #         (5, 8),  # ...
      #         (0, 9),
      #         (1, 1),
      #         (4, 7)
      #     ]
      # }
    return jobs

"""#MOR Greedy
Applichiamo la greedy chiamata Most Operations Remaining (MOR).
 La greedy mira a bilanciare i tempi complessivi dando priorità ai job con più operazioni da eseguire. In quanto l’alleato numero 1 della minimizzazione del makespan è il load balancing. essendo il makespan la durata del cammino critico -> facendo load balancing -> accorcio il cammino critico (perche le attività saranno piu distribuite) -> diminuisco il makespan. In caso di parità di scoring, cioè nel caso in cui due job hanno lo stesso numero di operazioni rimanenti viene applicato il cirterio di best MWR per decidere a chi dare priorità tra job dello spareggio.




"""

#----GREEDY----
def MOR_greedy(instance, jobs):
  # 1. Organizziamo i dati per accesso rapido
  job_ids = list(jobs.keys())

  # --- INIZIALIZZAZIONE STATO DEL SISTEMA ---

  # PUNTATORE: Indica a quale operazione è arrivato ogni job.
  # es: next_op_idx['1'] = 0 significa che il Job 1 deve ancora fare la prima op.
  next_op_idx = {j: 0 for j in job_ids}

  # TEMPO DISPONIBILITÀ JOB (Vincolo Tecnologico):
  # Un job non può iniziare l'operazione (i+1) prima che finisca l'operazione (i).
  # All'inizio tutti i job sono disponibili al tempo 0.
  job_available_time = {j: 0 for j in job_ids}

  # Identifichiamo le macchine uniche
  machines = set(op['machine'] for op in instance)

  # TEMPO DISPONIBILITÀ MACCHINA (Vincolo Risorsa):
  # Una macchina può processare solo un pezzo alla volta.
  # machine_available_time[M] indica quando la macchina M finirà il lavoro corrente.
  # inizialmente (non essendoci jobs in esecuzione) sono inizializzate a 0
  machine_available_time = {m: 0 for m in machines}

  results = [] # Lista dove salveremo lo schedule finale (Gantt)

  completed_jobs = 0
  total_jobs = len(job_ids)

  # --- CICLO DI SIMULAZIONE ---
  # Continua finché tutti i job non hanno finito tutte le loro operazioni
  while completed_jobs < total_jobs:

      # A. IDENTIFICAZIONE CANDIDATI
      # Chi è pronto a lavorare? Solo la PROSSIMA operazione di ogni job.
      candidates = []
      for j in job_ids:
          # Se il job j ha ancora operazioni da fare...
          if next_op_idx[j] < len(jobs[j]):
              # ...prendiamo l'operazione puntata dall'indice
              op = jobs[j][next_op_idx[j]]
              candidates.append(op)

      if not candidates:
          break # Sicurezza: nessun lavoro rimasto

      # B. CREAZIONE CODE PER MACCHINA
      # Raggruppiamo i candidati in base alla macchina che richiedono.
      # Es: Job 1 vuole M0, Job 2 vuole M1, Job 3 vuole M0 -> Coda su M0: [J1, J3]
      machine_queue = {m: [] for m in machines}
      for op in candidates:
          machine_queue[op['machine']].append(op)

      # C. RISOLUZIONE CONFLITTI (Core dell'algoritmo)
      for m in machines:
          queue = machine_queue[m]

          # Se nessuno vuole questa macchina in questo turno, passa alla prossima
          if not queue:
              continue

          # --- CALCOLO PRIORITÀ (MOR) ---
          scored_queue = []
          for op in queue:
              j_id = op['job']

              # Guardiamo quante operazioni mancano DOPO questa
              # Qui guardiamo il numero di op residuo totale inclusa l'operazione corrente
              # [next_op_idx[j_id]:]: cosi facendo prendo la lista delle operazioni di ogni job con
              # indice j_id fino alla fine A PARTIRE da next_op_idx[j_id]
              remaining_ops_list = jobs[j_id][next_op_idx[j_id]:]

              # Most Operations Remaining: Priorità a chi ha più passaggi da fare (cammino lungo nel grafo)
              score = len(remaining_ops_list)


              scored_queue.append((score, op))

          # Ordiniamo la coda: SCORE PIÙ ALTO VINCE (Reverse=True)
          scored_queue.sort(key=lambda x: x[0], reverse=True)

          # nel caso in cui piu job hanno score uguale chiamiamo una greedy due step (MWR_greedy).
          if (len(scored_queue) >= 2 and scored_queue[0] == scored_queue[1]):
            # visto che l'operaizone che viene schedulata è la prima della lista, prendo come riferimento
            # quel primo elemento
            max_score = scored_queue[0][0]
            top_jobs = list(takewhile(lambda x: x[0] == max_score, scored_queue))

            # GREEDY DUE STEP---calcolo priorità con MWR
            scored_queue2 = []
            for op in queue:
                j_id = op['job']

                # Calcoliamo la SOMMA delle durate di tutte le operazioni
                # che quel job deve ancora fare (dalla corrente alla fine)
                remaining_ops = jobs[j_id][next_op_idx[j_id]:]
                total_work_remaining = sum(o['duration'] for o in remaining_ops)

              # Il punteggio è il carico di lavoro totale residuo
                score = total_work_remaining


                scored_queue2.append((score, op))

            # Ordiniamo decrescente: chi ha PIÙ lavoro rimanente ha la priorità
            # come gestiamo due lavori con score pari?
            scored_queue2.sort(key=lambda x: x[0], reverse=True)

            # --- SELEZIONE DEL VINCITORE della lista del secondo step---
            best_op = scored_queue2[0][1]
            j_id = best_op['job']
            duration = best_op['duration']
          else:
            # --- SELEZIONE DEL VINCITORE della lista del primo step---
            best_op = scored_queue[0][1]
            j_id = best_op['job']
            duration = best_op['duration']

          # --- CALCOLO TEMPI (Schedulazione Semi-Attiva) ---
          # L'operazione può iniziare solo quando:
          # 1. Il Job è arrivato alla macchina (ha finito l'op precedente) -> job_available_time
          # 2. La Macchina si è liberata dal job precedente -> machine_available_time
          start_time = max(job_available_time[j_id], machine_available_time[m])
          end_time = start_time + duration

          # Salviamo il risultato
          results.append({
              'job': j_id,
              'machine': m,
              'start': start_time,
              'duration': duration,
              'op': best_op['op']
          })

          # --- AGGIORNAMENTO STATO ---
          # Ora la macchina è occupata fino a 'end_time'
          machine_available_time[m] = end_time
          # Ora il job è occupato fino a 'end_time'
          job_available_time[j_id] = end_time
          # Spostiamo il puntatore del job alla prossima operazione
          next_op_idx[j_id] += 1

          # Controlliamo se il job è finito completamente
          if next_op_idx[j_id] == len(jobs[j_id]):
              completed_jobs += 1

          # In questa versione semplificata, assegniamo un'operazione per macchina
          # e poi ricalcoliamo tutto al prossimo ciclo while.

  return results

"""#MWR Greedy
Applichiamo la greedy chiamata Most Working Remaining (MWR). La greedy mira a bilanciare i tempi complessivi dando priorità ai job con più lavoro ancora da eseguire. In caso di parità di scoring, cioè nel caso in cui due job hanno lo stesso lavoro rimanente viene applicato il cirterio di best MOR per decidere a chi dare priorità tra job dello spareggio.
"""

#----GREEDY----
def MWR_greedy(instance, jobs):
  # 1. Organizziamo i dati per accesso rapido
  job_ids = list(jobs.keys())

  # --- INIZIALIZZAZIONE STATO DEL SISTEMA ---

  # PUNTATORE: Indica a quale operazione è arrivato ogni job.
  # es: next_op_idx['1'] = 0 significa che il Job 1 deve ancora fare la prima op.
  next_op_idx = {j: 0 for j in job_ids}

  # TEMPO DISPONIBILITÀ JOB (Vincolo Tecnologico)(vincolo congiuntivo):
  # Un job non può iniziare l'operazione (i+1) prima che finisca l'operazione (i).
  # All'inizio tutti i job sono disponibili al tempo 0.
  job_available_time = {j: 0 for j in job_ids}

  # Identifichiamo le macchine uniche
  machines = set(op['machine'] for op in instance)

  # TEMPO DISPONIBILITÀ MACCHINA (Vincolo Risorsa)(Vincolo disgiuntivo):
  # Una macchina può processare solo un pezzo alla volta.
  # machine_available_time[M] indica quando la macchina M finirà il lavoro corrente.
  machine_available_time = {m: 0 for m in machines}

  results = [] # Lista dove salveremo lo schedule finale

  completed_jobs = 0
  total_jobs = len(job_ids)

  # --- CICLO DI SIMULAZIONE ---
  # Continua finché tutti i job non hanno finito tutte le loro operazioni
  while completed_jobs < total_jobs:

      # A. IDENTIFICAZIONE CANDIDATI
      # Chi è pronto a lavorare? Solo la PROSSIMA operazione di ogni job.
      candidates = []
      for j in job_ids:
          # Se il job j ha ancora operazioni da fare...
          if next_op_idx[j] < len(jobs[j]):
              # ...prendiamo l'operazione puntata dall'indice
              op = jobs[j][next_op_idx[j]]
              candidates.append(op)

      if not candidates:
          break # Sicurezza: nessun lavoro rimasto

      # B. CREAZIONE CODE PER MACCHINA
      # Raggruppiamo i candidati in base alla macchina che richiedono.
      # Es: Job 1 vuole M0, Job 2 vuole M1, Job 3 vuole M0 -> Coda su M0: [J1, J3]
      machine_queue = {m: [] for m in machines}
      for op in candidates:
          machine_queue[op['machine']].append(op)

      # C. RISOLUZIONE CONFLITTI (Core dell'algoritmo)
      for m in machines:
          queue = machine_queue[m]

          # Se nessuno vuole questa macchina in questo turno, passa alla prossima
          if not queue:
              continue

          # --- CALCOLO PRIORITÀ (MWR) ---
          scored_queue = []
          for op in queue:
              j_id = op['job']

              # Calcoliamo la SOMMA delle durate di tutte le operazioni
              # che quel job deve ancora fare (dalla corrente alla fine)
              remaining_ops = jobs[j_id][next_op_idx[j_id]:]
              total_work_remaining = sum(o['duration'] for o in remaining_ops)

             # Il punteggio è il carico di lavoro totale residuo
              score = total_work_remaining


              scored_queue.append((score, op))

          # Ordiniamo decrescente: chi ha PIÙ lavoro rimanente ha la priorità
          # come gestiamo due lavori con score pari?
          scored_queue.sort(key=lambda x: x[0], reverse=True)

          # nel caso in cui piu job hanno score uguale chiamiamo una greedy due step (MWR_greedy).
          if (len(scored_queue) >= 2 and scored_queue[0] == scored_queue[1]):
            # visto che l'operaizone che viene schedulata è la prima della lista, prendo come riferimento
            # quel primo elemento
            max_score = scored_queue[0][0]
            top_jobs = list(takewhile(lambda x: x[0] == max_score, scored_queue))

            # GREEDY DUE STEP---calcolo priorità con MOR
            scored_queue2 = []
            for op in queue:
                j_id = op['job']

                # Guardiamo quante operazioni mancano DOPO questa
                # Qui guardiamo il numero di op residuo totale inclusa l'operazione corrente
                # [next_op_idx[j_id]:]: cosi facendo prendo la lista delle operazioni di ogni job con
                # indice j_id fino alla fine A PARTIRE da next_op_idx[j_id]
                remaining_ops_list = jobs[j_id][next_op_idx[j_id]:]

                # Most Operations Remaining: Priorità a chi ha più passaggi da fare (cammino lungo nel grafo)
                score = len(remaining_ops_list)


                scored_queue2.append((score, op))

            # Ordiniamo la coda: SCORE PIÙ ALTO VINCE (Reverse=True)
            scored_queue2.sort(key=lambda x: x[0], reverse=True)

            # --- SELEZIONE DEL VINCITORE della lista del secondo step---
            best_op = scored_queue2[0][1]
            j_id = best_op['job']
            duration = best_op['duration']
          else:
            # --- SELEZIONE DEL VINCITORE della lista del primo step---
            best_op = scored_queue[0][1]
            j_id = best_op['job']
            duration = best_op['duration']

          # --- CALCOLO TEMPI (Schedulazione Semi-Attiva) ---
          # L'operazione può iniziare solo quando:
          # 1. Il Job ha finito l'op precedente -> job_available_time
          # 2. La Macchina si è liberata dal job precedente -> machine_available_time
          start_time = max(job_available_time[j_id], machine_available_time[m])
          end_time = start_time + duration

          # Salviamo il risultato
          results.append({
              'job': j_id,
              'machine': m,
              'start': start_time,
              'duration': duration,
              'op': best_op['op']
          })

          # --- AGGIORNAMENTO STATO ---
          # Ora la macchina è occupata fino a 'end_time'
          machine_available_time[m] = end_time
          # Ora il job è occupato fino a 'end_time'
          job_available_time[j_id] = end_time
          # Spostiamo il puntatore del job alla prossima operazione
          next_op_idx[j_id] += 1

          # Controlliamo se il job è finito completamente
          if next_op_idx[j_id] == len(jobs[j_id]):
              completed_jobs += 1

          # assegniamo un'operazione per macchina
          # e poi ricalcoliamo tutto al prossimo ciclo while.

  return results

"""#LPT Greedy:
Se una macchina si libera, l'operazione con il tempo di lavorazione più lungo rimanente tra quelli disponibili viene elaborato per primo.
"""

def LPT_greedy(istance, jobs):

    #1. Organizziamo i dati per accesso rapido
    job_ids = list(jobs.keys())

    # TEMPO DISPONIBILITÀ JOB (Vincolo Tecnologico):
    # Un job non può iniziare l'operazione (i+1) prima che finisca l'operazione (i).
    # All'inizio tutti i job sono disponibili al tempo 0.
    job_available_time = {j: 0 for j in job_ids}

    # Identifichiamo le macchine uniche
    machines = set(item['machine'] for item in istance)

    # TEMPO DISPONIBILITÀ MACCHINA (Vincolo Risorsa):
    # Una macchina può processare solo un pezzo alla volta.
    # machine_available_time[M] indica quando la macchina M finirà il lavoro corrente.
    machine_available_time = {m: 0 for m in machines}


    results = [] # Lista dove salveremo lo schedule finale (Gantt)

    completed_jobs = 0
    total_jobs = len(job_ids)

    #PUNTATORE: Indica a quale operazione è arrivato ogni job.
    # es: next_op_idx['1'] = 0 significa che il Job 1 deve ancora fare la prima op.
    next_op_idx = {j: 0 for j in job_ids}

    completed_jobs = 0
    total_jobs = len(job_ids)

    # --- CICLO DI SIMULAZIONE ---
    # Continua finché tutti i job non hanno finito tutte le loro operazioni
    while completed_jobs < total_jobs:

        # A. IDENTIFICAZIONE CANDIDATI
        # Chi è pronto a lavorare? Solo la PROSSIMA operazione di ogni job.
        candidates = []
        for j in job_ids:
            # Se il job j ha ancora operazioni da fare...
            if next_op_idx[j] < len(jobs[j]):
                # ...prendiamo l'operazione puntata dall'indice
                op = jobs[j][next_op_idx[j]]
                candidates.append(op)

        if not candidates:
            break # Sicurezza: nessun lavoro rimasto

        # B. CREAZIONE CODE PER MACCHINA
        # Raggruppiamo i candidati in base alla macchina che richiedono.
        # Es: Job 1 vuole M0, Job 2 vuole M1, Job 3 vuole M0 -> Coda su M0: [J1, J3]
        machine_queue = {m: [] for m in machines}
        for op in candidates:
            machine_queue[op['machine']].append(op)

        # prendo come job da eseguire quello con durata piu lunga
        # questo procedimento va fatto per ogni macchina
        score = []
        for m in machines:

            score = machine_queue[m]

            if not score:  # Se la coda è vuota, salta questa macchina
                continue

            score.sort(key=lambda x: x['duration'], reverse=True)

            # --- SELEZIONE DEL VINCITORE ---
            best_op = score[0]
            j_id = best_op['job']
            duration = best_op['duration']
            #--- CALCOLO TEMPI (Schedulazione Semi-Attiva) ---
                # L'operazione può iniziare solo quando:
                # 1. Il Job ha finito l'op precedente -> job_available_time
                # 2. La Macchina si è liberata dal job precedente -> machine_available_time
            start_time = max(job_available_time[j_id], machine_available_time[m])
            end_time = start_time + duration

            # Salviamo il risultato
            results.append({
                'job': j_id,
                'machine': m,
                'start': start_time,
                'duration': duration,
                'op': best_op['op']
            })

            # --- AGGIORNAMENTO STATO ---
            # Ora la macchina è occupata fino a 'end_time'
            machine_available_time[m] = end_time
            # Ora il job è occupato fino a 'end_time'
            job_available_time[j_id] = end_time
            # Spostiamo il puntatore del job alla prossima operazione
            next_op_idx[j_id] += 1

            # Controlliamo se il job è finito completamente
            if next_op_idx[j_id] == len(jobs[j_id]):
                completed_jobs += 1

    return results

"""#Calcolo makespan

"""

def calculate_makespan(results):
  """
  Calcola il Makespan di uno scheduling.

  Parametri:
  results: Lista di dizionari (output della funzione greedy).

  Ritorna:
  int/float: Il valore del Makespan (Cmax).
  """
  if not results:
    return 0

  # Per ogni operazione calcoliamo l'istante di fine: fine = inizio + durata
  # Il makespan è il massimo tra tutti questi istanti di fine.
  completion_times = [op['start'] + op['duration'] for op in results]
  makespan = max(completion_times)

  return makespan

"""# Individuazione del cammino critico"""

def find_critical_path(results):
    # Aggiungiamo il campo 'end' per facilitare i calcoli
    results_with_end = []
    for op_data in results:
        op_data_with_end = op_data.copy()
        op_data_with_end['end'] = op_data_with_end['start'] + op_data_with_end['duration']
        results_with_end.append(op_data_with_end)

    # Ordiniamo per tempo di fine decrescente
    sorted_res = sorted(results_with_end, key=lambda x: x['end'], reverse=True)
    c_max = sorted_res[0]['end']

    path = []
    current_op = sorted_res[0]
    path.append(current_op)

    while True:
        # Cerchiamo l'operazione che termina esattamente quando inizia current_op
        # e che sia o lo stesso job o sulla stessa macchina
        found = False
        for op in results_with_end:
            if op['end'] == current_op['start']:
                if op['job'] == current_op['job'] or op['machine'] == current_op['machine']:
                    current_op = op
                    path.append(op)
                    found = True
                    break
        if not found: break

    # Rimuovi la chiave 'end' aggiunta internamente per coerenza con il formato originale
    for op in path:
        if 'end' in op:
            del op['end']

    return list(reversed(path))

"""# Funzioni per individuare i blocchi e fare gli swap"""

def _op_id(op):
    """Genera un identificativo univoco (Job, Task) per l'operazione."""
    return (str(op['job']), int(op['op']))

def identifica_blocchi(cammino):
    """
    Raggruppa operazioni critiche consecutive sulla stessa macchina.
    Un blocco esiste solo se ci sono almeno 2 operazioni sulla stessa macchina.
    """
    blocchi = []
    if not cammino: return []
    blocco_attuale = [cammino[0]]
    for i in range(1, len(cammino)):
        if cammino[i]['machine'] == cammino[i-1]['machine']:
            blocco_attuale.append(cammino[i])
        else:
            if len(blocco_attuale) > 1:
                blocchi.append(list(blocco_attuale))
            blocco_attuale = [cammino[i]]
    if len(blocco_attuale) > 1:
        blocchi.append(blocco_attuale)
    return blocchi

def genera_vicini_blocco(blocco):
    """
    Genera le mosse basate sull'intorno N1 (Nowicki-Smutnicki).
    Ritorna una lista di tuple (id_op1, id_op2) da scambiare.
    """
    mosse = []
    if len(blocco) >= 2:
        # Mossa 1: Scambio le prime due operazioni del blocco
        mosse.append((_op_id(blocco[0]), _op_id(blocco[1])))

        # Mossa 2: Scambio le ultime due operazioni del blocco (se diverse dalle prime)
        if len(blocco) > 2:
            mosse.append((_op_id(blocco[-2]), _op_id(blocco[-1])))
    return mosse



def applica_swap_e_shift(schedule, mossa_swap):
    """
    Applica lo swap e ricalcola i tempi con Left-Shift.
    Usa l'algoritmo di Kahn per l'ordinamento topologico.
    """
    id1, id2 = mossa_swap
    new_schedule = [op.copy() for op in schedule]
    ops_dict = { _op_id(op): op for op in new_schedule }

    # 1. Determina le sequenze attuali sulle macchine
    machine_sequences = {}
    for op in sorted(new_schedule, key=lambda x: (x['machine'], x['start'])):
        m = op['machine']
        if m not in machine_sequences: machine_sequences[m] = []
        machine_sequences[m].append(_op_id(op))

    # 2. Applica lo swap nella sequenza della macchina specifica
    for m in machine_sequences:
        seq = machine_sequences[m]
        if id1 in seq and id2 in seq:
            idx1, idx2 = seq.index(id1), seq.index(id2)
            seq[idx1], seq[idx2] = seq[idx2], seq[idx1]
            break

    # 3. Costruzione del Grafo delle Precedenze
    adj = { oid: [] for oid in ops_dict }
    in_degree = { oid: 0 for oid in ops_dict }

    def add_edge(u, v):
        adj[u].append(v)
        in_degree[v] += 1

    # Vincoli dei Job (Successione task)
    job_groups = {}
    for oid in ops_dict: job_groups.setdefault(oid[0], []).append(oid)
    for j in job_groups:
        sorted_j = sorted(job_groups[j], key=lambda x: int(x[1]))
        for i in range(len(sorted_j)-1):
            add_edge(sorted_j[i], sorted_j[i+1])

    # Vincoli delle Macchine (Ordine post-swap)
    for m in machine_sequences:
        seq = machine_sequences[m]
        for i in range(len(seq)-1):
            add_edge(seq[i], seq[i+1])

    # 4. Ordinamento Topologico (Kahn)
    queue = [u for u in in_degree if in_degree[u] == 0]
    topo_order = []
    starts = { u: 0 for u in ops_dict }

    while queue:
        u = queue.pop(0)
        topo_order.append(u)
        finish_u = starts[u] + ops_dict[u]['duration']
        for v in adj[u]:
            starts[v] = max(starts[v], finish_u)
            in_degree[v] -= 1
            if in_degree[v] == 0:
                queue.append(v)

    # Se len(topo_order) < totale, abbiamo un ciclo (mossa non valida)
    if len(topo_order) < len(ops_dict):
        raise ValueError("Ciclo rilevato: mossa non ammissibile.")

    # 5. Aggiornamento dei risultati
    for oid, op in ops_dict.items():
        op['start'] = starts[oid]
        op['end'] = starts[oid] + op['duration']

    return list(ops_dict.values())

"""# Local search"""

def local_search(initial_schedule, max_iterations=100):
    current_schedule = initial_schedule
    current_makespan = calculate_makespan(current_schedule)

    history = [(0, current_makespan)]
    iteration=0

    for _ in range(max_iterations):
        found_improvement = False
        cp = find_critical_path(current_schedule)
        blocchi = identifica_blocchi(cp)


        best_neighbor = None
        best_neighbor_makespan = current_makespan


        for blocco in blocchi:

            candidati_vicini = genera_vicini_blocco(blocco)

            for v_blocco in candidati_vicini:

                try:
                    candidate_sched = applica_swap_e_shift(current_schedule, v_blocco)
                    m = calculate_makespan(candidate_sched)

                    if m < best_neighbor_makespan:
                        best_neighbor_makespan = m
                        best_neighbor = candidate_sched
                        found_improvement = True

                except ValueError:
                    continue


        if found_improvement:
            current_schedule = best_neighbor
            current_makespan = best_neighbor_makespan
            history.append((iteration, best_neighbor_makespan))
        else:
            break # Ottimo locale raggiunto
        iteration += 1

    print(f"\n=== Local Search2 Terminata ===")
    print(f"Iterazioni totali: {iteration}")
    print(f"Makespan iniziale: {calculate_makespan(initial_schedule)}")
    print(f"Makespan finale: {current_makespan}")
    print(f"Miglioramento: {calculate_makespan(initial_schedule) - current_makespan}")

    return current_schedule,current_makespan,history

"""# Simulated Annealing"""

def simulated_annealing(schedule, max_iterations=10, initial_temp=100.0, cooling_rate=0.95, patience=50):
    """
    Simulated Annealing con swap di blocchi e left-shift.

    Args:
        schedule: soluzione iniziale (lista di operazioni)
        max_iterations: numero massimo di iterazioni per temperatura
        initial_temp: temperatura iniziale
        cooling_rate: fattore di raffreddamento (0 < cooling_rate < 1)
        patience: numero massimo di non miglioramenti consecutivi

    Returns:
        best_schedule: migliore soluzione trovata
        best_makespan: makespan della migliore soluzione
        history: storico di makespan e iterazioni
    """

# Inizializzazione
    current_schedule = [op.copy() for op in schedule]
    current_makespan = calculate_makespan(current_schedule)

    best_schedule = [op.copy() for op in current_schedule]
    best_makespan = current_makespan

    iteration = 0
    history = [(iteration, current_makespan)]
    temperature = initial_temp
    no_improve_count = 0

    while temperature > 1e-4 and no_improve_count < patience:
        improved_globally = False

        for _ in range(max_iterations):
            # 1. Analisi e scelta mossa casuale
            cp = find_critical_path(current_schedule)
            blocchi = identifica_blocchi(cp)
            mosse = []
            for b in blocchi: mosse.extend(genera_vicini_blocco(b))

            if not mosse: break
            mossa = random.choice(mosse)

            try:
                candidate_sched = applica_swap_e_shift(current_schedule, mossa)
                candidate_makespan = calculate_makespan(candidate_sched)

                # Calcolo del Delta (Differenza di costo/makespan)
                delta = candidate_makespan - current_makespan


                # CASO 1: DELTA < 0 (Miglioramento)
                if delta < 0:
                    # Accettiamo sempre la mossa
                    current_schedule = candidate_sched
                    current_makespan = candidate_makespan

                    # Verifichiamo se è il record assoluto (Best Ever)
                    if current_makespan < best_makespan:
                        best_makespan = current_makespan
                        best_schedule = copy.deepcopy(current_schedule)
                        improved_globally = True


                # CASO 2: DELTA >= 0 (Peggioramento o Stagnazione)
                else:
                    # Calcoliamo la probabilità di accettazione (Criterio di Metropolis)
                    probabilita = math.exp(-delta / temperature)

                    if random.random() < probabilita:
                        # Accettiamo la mossa peggiore per esplorare nuove aree
                        current_schedule = candidate_sched
                        current_makespan = candidate_makespan
                    # Altrimenti la mossa viene scartata e restiamo dove siamo


            except ValueError:
                continue

        # Gestione della pazienza e del raffreddamento
        if improved_globally:
            no_improve_count = 0
        else:
            no_improve_count += 1

        history.append((iteration, current_makespan))
        iteration += 1
        temperature *= cooling_rate

    # Stampa i risultati finali dell'algoritmo
    print(f"\n=== Simulated Annealing Terminato ===")
    print(f"Iterazioni totali: {iteration}")
    print(f"Makespan iniziale: {calculate_makespan(schedule)}")
    print(f"Makespan migliore: {best_makespan}")
    print(f"Miglioramento: {calculate_makespan(schedule) - best_makespan}")

    return best_schedule, best_makespan, history

"""#MAIN - FLUSSO ESECUTIVO PER ISTANZE SMALL, MEDIUM, BIG

"""

# ====================================================================
# DEFINIZIONE ISTANZE: SMALL, MEDIUM, BIG
# ====================================================================

# SMALL INSTANCE (15x5 - istanza originale)
small_raw = """
15 5
1 58 2 44 3  5 0  9 4 58
1 89 0 97 4 96 3 77 2 84
0 77 1 87 2 81 4 39 3 85
3 57 1 21 2 31 0 15 4 73
2 48 0 40 1 49 3 70 4 71
3 34 4 82 2 80 0 10 1 22
1 91 4 75 0 55 2 17 3  7
2 62 3 47 1 72 4 35 0 11
0 64 3 75 4 50 1 90 2 94
2 67 4 20 3 15 0 12 1 71
0 52 4 93 3 68 2 29 1 57
2 70 0 58 1 93 4  7 3 77
3 27 2 82 1 63 4  6 0 95
1 87 2 56 4 36 0 26 3 48
3 76 2 36 0 36 4 15 1  8
"""

# MEDIUM INSTANCE (20x10 - istanza originale)
medium_raw = """
20 10
6 32 3 16 1 33 8 12 7 70 4 10 9 75 0 82 5 88 2 20
8 39 4 81 3 91 5 56 9 69 1 45 6 59 0 86 2 36 7 68
3 84 2 57 7 41 5 73 4 81 0 88 8 38 9 17 6 83 1  5
4 20 5  6 2 15 8 19 1 30 0 94 6 45 7 17 3 18 9 88
9 24 6 49 5 16 4 11 3 60 7  5 8 63 1 25 2 15 0 45
1 86 8 50 2 77 6 54 9 48 0 93 3 32 7 92 5 45 4 71
5 86 6 90 3 78 9 88 2 57 0 32 7 57 8 86 4 71 1 39
2 59 3 18 9 31 4 41 7 20 5 83 8 65 0 54 6 94 1 69
3 47 4 79 6 76 0 59 1 72 2  8 9 30 5 73 7 57 8 84
0 59 2 89 4 10 7 45 3  8 5 54 6 88 8 20 9  7 1 62
5 63 6  9 4 77 3 37 2  5 8 13 9 79 1 24 7 10 0 82
0 74 1 32 2 61 7 53 4 92 9 20 8 10 3  5 6 45 5 23
2 85 9 51 0 61 5 99 4 37 6 94 1 98 8 65 3 33 7 75
0 51 3 24 5  8 6 30 7 12 8 23 2  7 4 17 9 35 1 81
1 71 5 42 8 68 2 31 6 29 3 63 4 65 9 70 7 27 0 93
1 28 5 38 4 51 7 70 2 33 8 78 9 45 3 90 6 54 0 72
0 18 2 90 4 25 6 92 8 85 5 35 7 29 1 81 9 80 3 59
5 67 2 96 1 38 4 86 0 97 3 94 7 86 6 35 9 82 8 45
2 92 8 51 4 59 6 52 5  8 9 70 1 75 3 54 7 60 0 33
3 98 7 80 5 78 0 82 2  7 9 89 1 69 4 51 8 79 6 62
"""

# BIG INSTANCE (30x10 - istanza originale)
big_raw = """
30 10
0 66 2 84 3 26 7 29 9 94 6 98 8  7 5 98 1 45 4 43
3 32 0 97 6 55 2 88 8 93 9 88 1 20 4 50 7 17 5  5
4 43 3 68 8 47 9 68 1 57 6 20 5 81 2 60 7 94 0 62
1 57 5 40 0 78 6  9 2 49 9 17 3 32 4 30 8 87 7 77
0 52 4 30 3 48 5 48 1 26 9 17 6 93 8 97 7 49 2 89
7 95 0 33 1  5 6 17 5 70 3 57 4 34 2 61 8 62 9 39
7 97 5 92 1 31 8  5 2 79 4  5 3 67 0  5 9 78 6 60
2 79 4  6 7 20 8 45 6 34 3 24 9 26 5 68 1 16 0 46
7 58 9 50 2 19 8 93 6 49 3 25 5 85 4 50 0 93 1 26
9 81 6 71 5  7 1 39 2 16 8 42 0 71 4 84 3 56 7 99
8  9 0 86 9  6 3 71 6 97 5 85 4 16 2 42 7 81 1 81
4 72 3 24 0 30 8 56 2 43 1 61 7 82 6 40 5 59 9 43
9 43 1 13 6 70 7 93 0 95 8 12 4 15 2 78 5 97 3 14
0 14 6 26 1 71 3 46 8 80 5 31 4 37 9 27 7 92 2 67
2 12 0 43 5 96 6  7 3 45 7 20 1 13 9 29 4 60 8 33
1 78 5 50 6 84 0 42 8 84 4 30 9 76 2 57 7 87 3 59
4 49 7 50 1 15 8 13 0 93 6 50 9 32 5 59 3 10 2 35
1 25 0 47 7 60 8 33 4 53 5 37 9 73 2 22 3 87 6 79
0 84 6 83 1 71 5 68 9 89 8 11 3 60 4 50 2 33 7 97
1 14 0 38 6 88 5  5 4 77 7 92 8 24 2 73 9 52 3 71
7 62 9 19 6 38 3 15 8 64 2 64 4  8 1 61 0 19 5 33
2 33 5 46 4 74 0 56 6 84 9 83 8 19 7  8 3 32 1 97
4 50 3 71 6 50 2 97 9  8 0 17 7 19 8 92 5 54 1 52
8 32 1 79 3 97 5 38 9 49 4 76 6 76 0 56 2 78 7 54
5 13 3  5 2 25 0 86 1 95 9 28 6 78 8 24 7 10 4 39
7 48 2 59 0 20 9  7 5 31 6 97 1 89 4 32 3 25 8 41
5 87 0 18 9 48 2 43 1 30 6 97 7 47 8 65 3 69 4 27
6 71 5 20 8 20 1 78 3 39 0 17 7 50 2 44 9 42 4 38
0 50 9 42 3 72 5  7 1 77 7 58 4 78 2 89 6 70 8 36
3 32 9 95 2 13 0 73 6 97 8 24 4 49 5 57 1 68 7 94
"""

# ====================================================================
# FUNZIONE PER ESEGUIRE IL FLUSSO PER OGNI ISTANZA
# ====================================================================

def run_instance_workflow(instance_name, raw_instance):
    """
    Esegue il flusso completo per un'istanza:
    - MOR: Greedy -> Local Search e Greedy -> Simulated Annealing
    - MWR: Greedy -> Local Search e Greedy -> Simulated Annealing
    - LPT: Greedy -> Local Search e Greedy -> Simulated Annealing
    
    Crea un grafico che confronta i makespan trovati rispetto all'ottimo.
    """
    
    print("\n" + "="*80)
    print(f"ISTANZA: {instance_name}".center(80))
    print("="*80)
    
    # Parsing istanza
    instance, n_j, n_m = parse_benchmark_instance(raw_instance)
    parsed_jobs = parse_instance(instance)

    # Dizionario per raccogliere i tempi (ms) con timer ad alta risoluzione
    timings_ms = {}
    
    # Calcolo ottimo con solver
    print("\nCalcolo dell'ottimo con Solver...")
    t0_ns = time.perf_counter_ns()
    optimum = solver(instance)
    timings_ms['Solver'] = (time.perf_counter_ns() - t0_ns) / 1_000_000
    print(f"Ottimo trovato: {optimum}\n")
    
    # Dizionario per raccogliere i risultati
    results = {
        'Ottimo (Solver)': optimum
    }
    
    greedy_functions = {
        'MOR': MOR_greedy,
        'MWR': MWR_greedy,
        'LPT': LPT_greedy
    }
    
    # Per ogni algoritmo greedy
    for greedy_name, greedy_func in greedy_functions.items():
        print(f"\n--- Processing {greedy_name} ---")
        
        # 1. Esegui greedy
        t0_ns = time.perf_counter_ns()
        greedy_schedule = greedy_func(instance, parsed_jobs)
        timings_ms[f'{greedy_name}\nGreedy'] = (time.perf_counter_ns() - t0_ns) / 1_000_000
        greedy_makespan = calculate_makespan(greedy_schedule)
        print(f"{greedy_name} Greedy Makespan: {greedy_makespan}")
        results[f'{greedy_name}\nGreedy'] = greedy_makespan
        plot_job_shop(greedy_schedule, title=f"Job Shop Scheduling ({greedy_name} Greedy) - Makespan: {greedy_makespan}")
        
        # 2. Local Search
        print(f"GANT CRITICAL PATH ")
        critical_path = find_critical_path(greedy_schedule)
        if critical_path:
            plot_job_shop(critical_path, title="Gantt Critical Path Soluzione Greedy MOR(iniziale)")
        else:
            print("Nessun cammino critico trovato.")
        print(f"Running Local Search on {greedy_name}...")

        t0_ns = time.perf_counter_ns()
        ls_best_schedule, ls_best_makespan, ls_history = local_search(
            greedy_schedule,
            max_iterations=100,
        )
        timings_ms[f'{greedy_name}\n+ LS'] = (time.perf_counter_ns() - t0_ns) / 1_000_000
        results[f'{greedy_name}\n+ LS'] = ls_best_makespan
        
        # 3. Simulated Annealing
        t0_ns = time.perf_counter_ns()
        sa_schedule, sa_makespan, sa_history = simulated_annealing(
            greedy_schedule,
            max_iterations=200,
            initial_temp=100.0,
            cooling_rate=0.95,
            patience=30
        )
        timings_ms[f'{greedy_name}\n+ SA'] = (time.perf_counter_ns() - t0_ns) / 1_000_000
        results[f'{greedy_name}\n+ SA'] = sa_makespan

        #4. Plot soluzione finale (Local Search)
        print(f"Makespan della soluzione {greedy_name} LC : {ls_best_makespan}")
        plot_job_shop(ls_best_schedule, title=f"Gantt Local Search - Makespan: {ls_best_makespan}")

        #5. Plot soluzione finale (Simulated Annealing)
        print(f"Makespan della soluzione {greedy_name} SA : {sa_makespan}")
        plot_job_shop(sa_schedule, title=f"Gantt Simulated Annealing - Makespan: {sa_makespan}")


        # 6. Plot storia del makespan (Local Search)
        print(f"PLOT EVOLUZIONE MAKESPAN {greedy_name} LC ")
        iterations, makespans = zip(*ls_history)
        fig_ls = plt.figure(figsize=(10, 6))
        plt.plot(iterations, makespans, marker='o', linestyle='-', linewidth=2, markersize=6)
        plt.xlabel('Iterazione', fontweight='bold')
        plt.ylabel('Makespan', fontweight='bold')
        plt.title('Evoluzione del Makespan durante Local Search', fontsize=14)
        plt.grid(True, alpha=0.5)
        plt.tight_layout()
        safe_show(fig_ls, title=f"{instance_name}_{greedy_name}_local_search")

        # 7. Plot storia del makespan (Simulated Annealing)
        print(f"PLOT EVOLUZIONE MAKESPAN {greedy_name} SA ")
        sa_iterations, sa_makespans = zip(*sa_history)
        fig_sa = plt.figure(figsize=(10, 6))
        plt.plot(sa_iterations, sa_makespans, marker='o', linestyle='-', linewidth=2, markersize=6)
        plt.xlabel('Iterazione', fontweight='bold')
        plt.ylabel('Makespan', fontweight='bold')
        plt.title('Evoluzione del Makespan durante Simulated Annealing', fontsize=14)
        plt.grid(True, alpha=0.5)
        plt.tight_layout()
        safe_show(fig_sa, title=f"{instance_name}_{greedy_name}_simulated_annealing")
    # ====================================================================
    # CREAZIONE GRAFICO PER L'ISTANZA
    # ====================================================================
    
    print(f"\nCreating comparison plot for {instance_name}...")
    
    # Preparazione dati per il grafico
    algorithms = list(results.keys())
    makespans = list(results.values())
    
    # Determinazione colori
    colors = []
    for alg in algorithms:
        if 'Ottimo' in alg:
            colors.append('#2ecc71')  # Verde
        elif 'Greedy' in alg and '+' not in alg:
            colors.append('#3498db')  # Blu
        elif 'LS' in alg:
            colors.append('#e74c3c')  # Rosso
        else:  # SA
            colors.append('#f39c12')  # Arancione
    
    # Creazione figura
    fig, ax = plt.subplots(figsize=(16, 8))
    bars = ax.bar(range(len(algorithms)), makespans, color=colors, edgecolor='black', linewidth=1.5, alpha=0.85)
    
    # Aggiunta dei valori sopra le barre
    for i, (bar, makespan) in enumerate(zip(bars, makespans)):
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
                f'{int(makespan)}',
                ha='center', va='bottom', fontweight='bold', fontsize=11)
    
    # Linea orizzontale per l'ottimo
    ax.axhline(y=optimum, color='green', linestyle='--', linewidth=2.5, label=f'Optimal: {optimum}', alpha=0.8)
    
    # Formattazione
    ax.set_xlabel('Algorithm', fontsize=13, fontweight='bold')
    ax.set_ylabel('Makespan', fontsize=13, fontweight='bold')
    ax.set_title(f'Makespan Comparison - Instance {instance_name}', fontsize=15, fontweight='bold', pad=15)
    ax.set_xticks(range(len(algorithms)))
    ax.set_xticklabels(algorithms, fontsize=10)
    ax.legend(fontsize=12, loc='upper right')
    ax.grid(True, axis='y', alpha=0.3, linestyle='--')
    
    plt.tight_layout()
    safe_show(fig, title=f"confronto_makespan_{instance_name}")

    # ====================================================================
    # CREAZIONE GRAFICO TEMPI DI ELABORAZIONE PER L'ISTANZA
    # ====================================================================
    print(f"\nCreating timing comparison plot for {instance_name}...")

    timing_labels = list(timings_ms.keys())
    timing_values = list(timings_ms.values())

    timing_colors = []
    for label in timing_labels:
        if label == 'Solver':
            timing_colors.append('#2ecc71')
        elif 'Greedy' in label and '+' not in label:
            timing_colors.append('#3498db')
        elif 'LS' in label:
            timing_colors.append('#e74c3c')
        else:
            timing_colors.append('#f39c12')

    fig_t, ax_t = plt.subplots(figsize=(16, 8))
    bars_t = ax_t.bar(
        range(len(timing_labels)),
        timing_values,
        color=timing_colors,
        edgecolor='black',
        linewidth=1.5,
        alpha=0.85
    )

    for bar, val in zip(bars_t, timing_values):
        ax_t.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height(),
            f"{val:.3f} ms",
            ha='center',
            va='bottom',
            fontweight='bold',
            fontsize=10
        )

    ax_t.set_xlabel('Method', fontsize=13, fontweight='bold')
    ax_t.set_ylabel('Processing Time (ms)', fontsize=13, fontweight='bold')
    ax_t.set_title(
        f'Processing Time Comparison - Instance {instance_name}',
        fontsize=15,
        fontweight='bold',
        pad=15
    )
    ax_t.set_xticks(range(len(timing_labels)))
    ax_t.set_xticklabels(timing_labels, fontsize=10)
    ax_t.grid(True, axis='y', alpha=0.3, linestyle='--')

    plt.tight_layout()
    safe_show(fig_t, title=f"confronto_tempi_{instance_name}")
    
    # Stampa tabellare
    print(f"\n{'Algorithm':<20} {'Makespan':>12} {'Gap %':>10} {'Gap (units)':>15}")
    print("-" * 60)
    for alg, ms in results.items():
        gap_pct = ((ms - optimum) / optimum * 100) if optimum > 0 else 0
        gap_units = ms - optimum
        print(f"{alg.replace(chr(10), ' '):<20} {int(ms):>12} {gap_pct:>9.2f}% {gap_units:>14.0f}")

    print(f"\n{'Method':<20} {'Time (ms)':>12}")
    print("-" * 36)
    for method, t_ms in timings_ms.items():
        print(f"{method.replace(chr(10), ' '):<20} {t_ms:>12.3f}")

    save_terminal_table_as_image(instance_name, results, optimum)
    
    return results


# ====================================================================
# ESECUZIONE WORKFLOW PER TUTTE LE ISTANZE
# ====================================================================

print("\n" + "="*100)
print("JOB SHOP SCHEDULING - COMPREHENSIVE ANALYSIS".center(100))
print("="*100)

results_small = run_instance_workflow("SMALL (15x5)", small_raw)
results_medium = run_instance_workflow("MEDIUM (20x10)", medium_raw)
results_big = run_instance_workflow("BIG (30x10)", big_raw)

print("\n" + "="*100)
print("ANALYSIS COMPLETE".center(100))
print("="*100)
